// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMfUt4wXwz3iOGmA61dDg5ZnOGdex5Oko',
    appId: '1:967886607779:web:3b7b661deb6270a7d77616',
    messagingSenderId: '967886607779',
    projectId: 'retreat2025-8256b',
    authDomain: 'retreat2025-8256b.firebaseapp.com',
    storageBucket: 'retreat2025-8256b.firebasestorage.app',
    measurementId: 'G-W11LGZ02HS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIdRn7tpFesy4ZcUZ-GTEEJLHqnK93y1g',
    appId: '1:967886607779:android:bf14f975f57fbf16d77616',
    messagingSenderId: '967886607779',
    projectId: 'retreat2025-8256b',
    storageBucket: 'retreat2025-8256b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeYDH9c6tMjIt3Hq3-tXjKVwMPSaPcvoc',
    appId: '1:967886607779:ios:882aeeb80741d0fcd77616',
    messagingSenderId: '967886607779',
    projectId: 'retreat2025-8256b',
    storageBucket: 'retreat2025-8256b.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );
}
